_target_: MemoryChatBotFlowModule.MemoryChatBotAtomicFlow.MemoryChatBotAtomicFlow.instantiate_from_default_config
name: ChatBotFlow
description: A conversational chatbot flow with integrated short-term memory.
enable_personal_memory: true
enable_memory: true
llm_backend:
  _target_: aiflows.backends.llm_lite.LiteLLMBackend
  api_infos: ???
  model_name:
    groq: groq/llama3-70b-8192
  'n': 1
  max_tokens: 1700
  temperature: 0.1
  top_p: 0.9
  stream: false
backend:
  _target_: aiflows.backends.llm_lite.LiteLLMBackend
  api_infos: ???
  model_name:
    groq: groq/llama3-70b-8192
  'n': 1
  max_tokens: 1700
  temperature: 0.1
  top_p: 0.9
  stream: false
prompt_template:
  _target_: aiflows.prompt_template.JinjaPrompt
  template: '

    Assistant: You are a helpful assistant engaged in a conversation with a user.

    You are an expert at answering questions based on the provided memories. Your
    task is to provide accurate and concise answers to the questions by leveraging
    the information given in the memories.


    Guidelines:

    - Extract relevant information from the memories based on the question.

    - If no relevant information is found, make sure you don''t say no information
    is found or we did not talk about it. Instead, accept the question and provide
    a general response.

    - Ensure that the answers are clear, concise, and directly address the question.


    Here is the memory context:


    {{memory_context}}


    User: {{user_message}}

    Assistant:'
  input_variables:
  - memory_context
  - user_message
collection_name: personal_meQ6m5556ory_c4o5lle4ction
persist_directory: ./vector_sYr4r4555557o554yr5y7e4yy
memory_backend:
  _target_: aiflows.backends.llm_lite.LiteLLMBackend
  api_infos: ???
  model_name:
    groq: groq/llama3-70b-8192
  'n': 1
  max_tokens: 1500
  temperature: 0.1
  top_p: 0.9
  stream: false
vector_backend:
  _target_: aiflows.backends.llm_lite.LiteLLMBackend
  api_infos:
  - _target_: aiflows.backends.api_info.ApiInfo
    backend_used: nomic
    api_key: nk-Bk1dpxBqP9_ozAoTAwredzaeuy2WBkpi06AGouKkKoU
    api_base: null
  model_name: ''
graph_config:
  provider: neo4j
  uri: neo4j+s://b344f2e5.databases.neo4j.io
  user: neo4j
  password: QqOeeksrY4izSIIQ2wMGeUClY81QnEayAc7ltBmtW-k
